### PR TITLE
add CORS headers to allow use of etherpad API inside browsers

### PR DESCRIPTION
**Pull request by oupala**
This pull request add CORS headers to allow use of etherpad API inside browsers.

### CODE REVIEW

**Comment by oupala** [comment]
By the way, I'm not sure this pull request is the best answer to the problem that we try to fix.

If we try to open the etherpad API inside browsers, the fix should not be specific to one plugin, it should be a global etherpad configuration flag to enable or not the API, and to enable or not the CORS header (and to which domains).

This has been discussed in another issue : [Suggesting new HTTP API](https://github.com/ether/etherpad-lite/issues/669#issuecomment-5305744).

**Comment by oupala** [comment]
Please @JohnMcLear can you please tell me if you will merge this pull request?

**Comment by JohnMcLear** [comment]
See http://mclear.co.uk

On 23 Aug 2016 7:14 p.m., oupala <notifications@github.com> wrote:

Please @JohnMcLear<https://github.com/JohnMcLear> can you please tell me if you will merge this pull request?

**Comment by oupala** [comment]
Will you transfert the whole repo (including issues), or simply clone it to their new home?

**Comment by oupala** [comment]
Now that the whole repo has been transferred, is there anyone who can merge this pull request?

**Comment by JohnMcLear** [comment]
@ether/team-plugins

**Comment by oupala** [comment]
Hi @JohnMcLear is there anyone un @ether/team-plugins ?

**Comment by JohnMcLear** [comment]
@oupala do you still want this?  If so I can look into it.

**Comment by oupala** [comment]
As the merge request is ready, yes please I'd like to see it merged.

**Comment by JohnMcLear** [comment]
The repo that submitted the PR has been deleted.. . So I can't merge.

**Comment by oupala** [comment]
Oups, I think that I waited for a merge for too long, so I finally cleaned my stalled repos.

As this pull request can display the changes, is there a way to merge it without the original repo?

If not, will it work if I recreate the repo?

If not, can you make the change by yourself, as the change is only one line long?

**Comment by JohnMcLear** [comment]
You will nede to remake the PR.

**Comment by oupala** [comment]
The new pull request is now available.

**Pull request closed without merging**
