### PR TITLE
fixed german translation

### PR DESCRIPTION
**Pull request by anoymouserver**

### CODE REVIEW

**Comment by anoymouserver** [comment]
The german translation is still wrong .. thats definitely french:

https://github.com/ether/ep_markdown/blob/5872dec91d7e29b02ae03c4aca4ceb1bf681afb8/locales/de.json#L5

**Comment by JohnMcLear** [comment]
Sorry but we don't manage translations within the software
They are managed on translatewiki.net

**Comment by JohnMcLear** [comment]
Please resolve the merge conflicts :)

**Comment by JohnMcLear** [comment]
cc @translatewiki

**Pull request merged**
